-- 코드를 입력하세요
SELECT NAME, DATETIME
FROM (
    SELECT I.ANIMAL_ID AS ID, I.DATETIME AS DATETIME, I.NAME AS NAME, O.DATETIME AS O_DATETIME
    FROM ANIMAL_INS AS I
    LEFT JOIN ANIMAL_OUTS AS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
)AS J
WHERE J.O_DATETIME IS NULL
ORDER BY DATETIME ASC
LIMIT 3;
