# -- 코드를 작성해주세요
# SELECT DIFFERENTIATION_DATE AS YEAR, MAX-SIZE_OF_COLONY AS YEAR_DEV, ID
# FROM (
#     SELECT ID,PARENT_ID,SIZE_OF_COLONY,YEAR(DIFFERENTIATION_DATE) AS DIFFERENTIATION_DATE
#     FROM ECOLI_DATA
# ) AS E
# INNER JOIN (
#     SELECT DIFFERENTIATION_DATE AS DATE, MAX(SIZE_OF_COLONY) AS MAX
#     FROM ECOLI_DATA
#     GROUP BY DIFFERENTIATION_DATE
# ) AS J
# ON J.DATE = E.DIFFERENTIATION_DATE
# ORDER BY YEAR, YEAR_DEV;

# # SELECT ID,PARENT_ID,SIZE_OF_COLONY,YEAR(DIFFERENTIATION_DATE) AS DIFFERENTIATION_DATE
# #     FROM ECOLI_DATA;

WITH MAXS AS (
SELECT MAX(SIZE_OF_COLONY) AS MAXSIZE
, YEAR(DIFFERENTIATION_DATE) AS YEAR
FROM ECOLI_DATA
GROUP BY YEAR )

SELECT M.YEAR
, (M.MAXSIZE - E.SIZE_OF_COLONY) AS YEAR_DEV
, E.ID
FROM MAXS AS M INNER JOIN ECOLI_DATA AS E
ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY M.YEAR, YEAR_DEV
