-- 코드를 작성해주세요
SELECT S.SUM AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES AS E
INNER JOIN(
    SELECT EMP_NO, SUM(SCORE) AS SUM
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
)AS S
ON S.EMP_NO = E.EMP_NO
ORDER BY S.SUM DESC
LIMIT 1;


