-- 코드를 입력하세요
SELECT F.CATEGORY, M.MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
INNER JOIN(
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING CATEGORY = '식용유' OR CATEGORY = '과자' OR CATEGORY = '국' OR CATEGORY = '김치'
    ORDER BY MAX_PRICE DESC
) M
ON M.MAX_PRICE = F.PRICE AND M.CATEGORY = F.CATEGORY
ORDER BY MAX_PRICE DESC;


# SELECT *
# FROM FOOD_PRODUCT;